### PR TITLE
Use normal user register form for account creation

### PR DESCRIPTION
**Pull request by brandonneil**

### CODE REVIEW

**Comment by genjohnson** [comment]
I tested this with a site locally, in combination with https://github.com/ITS-UofIowa/sitenow_core/pull/4. While webmasters are able to create user accounts and administrative accounts are protected as I'd expect, there are a couple of things I'd like to see addressed before this is committed:

- Require a role (editor or webmaster) to be selected on the user registration and user profile (edit) forms. I would like to avoid user accounts that have only the authenticated user role, since users with that role really can't do anything.
- Alter the user profile form (/user/UID/edit) so that the field labels and descriptions match those being used on the user registration form (eg., HawkID instead of Username).
- An email is being sent to users when the status of their account is changed from "blocked" to "active", and this email includes a one-time login link. If it wouldn't take a lot of effort, I'd like these emails to be disabled. If it looks like this would take a lot of effort, then I'd like to change the text of the email to remove the one-time login link.

While testing this I also noticed that users are being presented with a math captcha when creating user accounts. We should be using Hidden Captchas, and we may want authenticated users to skip captchas entirely. It's not a blocker for this pull request, but I have opened an issue for sitenow_forms regarding captcha configuration - https://github.com/ITS-UofIowa/sitenow_forms/issues/1.

**Comment by brandonneil** [comment]
I think these are all great requests! Which of these are regressions that we had before and do not now? #2?

I think we should spin off non-regressions into subsequent feature requests. Then, if someone gets to them before the next round of core/contrib/custom updates, we can add them in, if not, my opinion is not to hold up this PR on them.

**Comment by genjohnson** [comment]
Not requiring that a role be selected on the user registration form is a regression. However, this requirement wasn't previously being enforced on the user profile (edit) forms. I'd like this to at least be done on the registration form, though ideally a custom role would be required on both forms.

Whether altering the user profile form to have matching field labels/descriptions is a regression is debatable, since we had a different field setup before. I don't expect this to take much effort, so I'd like to see it addressed now.

It turns out emails being sent when user accounts are changed from "blocked" to "active" is not a regression, so another issue can be opened to address this.

**Comment by genjohnson** [comment]
I've pushed additional commits to address my first two concerns, and opened an issue (with proposed solution) about the third at https://github.com/ITS-UofIowa/sitenow_user_create/issues/3.

If someone besides me could review and approve these changes, then I'd say this branch is good to be merged in.

**Comment by joewhitsitt** [comment]
The core feature branch seems to work as expected.

@genjohnson requests/additions seem desirable as well. I see the hawkid alter but I was able to create a user with just authenticated role selected (default/disabled/selected) with no other roles without validation error. I don't see a red asterisks either for the roles field.

**Comment by richardbporter** [comment]
I tried this out locally and everything seems to work fine. I wasn't able to reproduce @joewhitsitt's issue of creating users with just authenticated user role. I also added a commit to disable the emails described in #3

**Comment by adamdelaney** [comment]
I have tested this locally and everything works as expected. I think we are should get a release out for this ASAP

**Pull request merged**
